name: deploy webapp to azure

env:
  AZURE_WEBAPP_NAME: folkmoz-ai
  NODE_VERSION: "20.x"
  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  AZURE_WEPAPP_PACKAGE_PATH: "."

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/*.yaml" # No longer Azure app service anymore
      - "README.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install, build
        run: |
          npm install
          npm run build --if-present

      - name: Copy necessary files to artifact staging directory
        run: |
          cp -R ./.next/standalone ./site-deploy
          cp -R ./.next/static ./site-deploy/.next/static
          cp -R ./public ./site-deploy/public

      - name: Zip artifact
        run: |
          cd site-deploy
          zip -r next-app.zip .
          mv next-app.zip ../
          cd ..

      - name: Diagnostic
        run: |
          ls -al
          ls -al site-deploy
          ls -al next-app.zip

      - name: Package and upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-app
          path: next-app.zip

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: next-app

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ github.workspace }}/next-app.zip
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

      - name: Cleanup
        run: |
          rm -rf ${{ github.workspace }}/next-app.zip

      - name: Check status
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net
